server:
  port: 9090

spring:
  config:
    import: optional:configserver:http://localhost:9111
  application:
    name: API-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EMPLOYEE-SERVICE
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeCircuitBreaker
                fallbackuri: forward:/employeeServiceFallback
        - id: SKILL-SERVICE
          uri: http://localhost:8082/
          predicates:
            - Path=/skill/**
          filters:
            - name: CircuitBreaker
              args:
                name: skillCircuitBreaker
                fallbackuri: forward:/skillServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix-stream

eureka:
  client:
    register-eith-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost