#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: abisheks
#    password: 12345678
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect


spring:
  application:
    name: SKILL-SERVICE
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  cloud:
    discovery:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9111


server:
  port: 8082